//
// Generated file, do not edit! Created by opp_msgtool 6.0 from content.msg.
//

#ifndef __CONTENT_M_H
#define __CONTENT_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0600
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif

class ContentMsg;
/**
 * Class generated from <tt>content.msg:2</tt> by opp_msgtool.
 * <pre>
 * message ContentMsg
 * {
 *     int source_num;
 *     char type;
 *     int destination;
 *     int hopCount = 0;
 *     char content;
 *     int chunk;
 *     int tcp_type;
 *     omnetpp::simtime_t c_average_chunk_arr;
 *     omnetpp::simtime_t c_finish_dwnl_time;
 *     omnetpp::simtime_t c_total_stall_time;
 *     int c_stall_count_size;
 * }
 * </pre>
 */
class ContentMsg : public ::omnetpp::cMessage
{
  protected:
    int source_num = 0;
    char type = 0;
    int destination = 0;
    int hopCount = 0;
    char content = 0;
    int chunk = 0;
    int tcp_type = 0;
    omnetpp::simtime_t c_average_chunk_arr = SIMTIME_ZERO;
    omnetpp::simtime_t c_finish_dwnl_time = SIMTIME_ZERO;
    omnetpp::simtime_t c_total_stall_time = SIMTIME_ZERO;
    int c_stall_count_size = 0;

  private:
    void copy(const ContentMsg& other);

  protected:
    bool operator==(const ContentMsg&) = delete;

  public:
    ContentMsg(const char *name=nullptr, short kind=0);
    ContentMsg(const ContentMsg& other);
    virtual ~ContentMsg();
    ContentMsg& operator=(const ContentMsg& other);
    virtual ContentMsg *dup() const override {return new ContentMsg(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual int getSource_num() const;
    virtual void setSource_num(int source_num);

    virtual char getType() const;
    virtual void setType(char type);

    virtual int getDestination() const;
    virtual void setDestination(int destination);

    virtual int getHopCount() const;
    virtual void setHopCount(int hopCount);

    virtual char getContent() const;
    virtual void setContent(char content);

    virtual int getChunk() const;
    virtual void setChunk(int chunk);

    virtual int getTcp_type() const;
    virtual void setTcp_type(int tcp_type);

    virtual omnetpp::simtime_t getC_average_chunk_arr() const;
    virtual void setC_average_chunk_arr(omnetpp::simtime_t c_average_chunk_arr);

    virtual omnetpp::simtime_t getC_finish_dwnl_time() const;
    virtual void setC_finish_dwnl_time(omnetpp::simtime_t c_finish_dwnl_time);

    virtual omnetpp::simtime_t getC_total_stall_time() const;
    virtual void setC_total_stall_time(omnetpp::simtime_t c_total_stall_time);

    virtual int getC_stall_count_size() const;
    virtual void setC_stall_count_size(int c_stall_count_size);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const ContentMsg& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, ContentMsg& obj) {obj.parsimUnpack(b);}


namespace omnetpp {

template<> inline ContentMsg *fromAnyPtr(any_ptr ptr) { return check_and_cast<ContentMsg*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __CONTENT_M_H

